
#define IDS_APP_TITLE			103
#define IDR_MAINFRAME			128
#define IDD_PHONEBOOKLARGE_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_PHONEBOOKLARGE			107
#define IDI_SMALL				108
#define IDC_PHONEBOOKLARGE			109
#define IDC_MYICON				2
#define IDC_LISTVIEW (HMENU)111
#define IDC_TELEDIT (HMENU)112
#define IDC_FNEDIT (HMENU)113
#define IDC_MNEDIT (HMENU)114
#define IDC_LNEDIT (HMENU)115
#define IDC_HSEDIT (HMENU)116
#define IDC_HSNGEDIT (HMENU)117
#define IDC_FLTEDIT (HMENU)118
#define IDC_STREDIT (HMENU)119
#define IDC_SEARCHBTN (HMENU)120
#define IDC_PREVBTN (HMENU)121
#define IDC_NEXTBTN (HMENU)122
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif

